*** Settings ***
Documentation       Shared keyword library entrypoint.

Resource            common.resource
Resource            locators.resource
Resource            button.resource
Resource            text.resource
Resource            textbox.resource
Resource            checkbox.resource
Resource            list.resource
Resource            messagebox.resource
Resource            notification.resource
