CREATE TYPE "LanguageLevel" AS ENUM (
  'A1_1',
  'A1_2',
  'A2_1',
  'A2_2'
);

CREATE TYPE "ExerciseType" AS ENUM (
  'MULTIPLE_CHOICE',
  'VOCABULARY_CHECK',
  'FILL_IN_BLANK',
  'SENTENCE_ORDER',
  'PRONUNCIATION_PRACTICE'
);

CREATE TYPE "SoundType" AS ENUM (
  'VOWEL',
  'CONSONANT',
  'DIPHTHONG',
  'UMLAUT'
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "description" varchar,
  "image_src" varchar,
  "level" LanguageLevel,
  "order" int,
  "is_active" boolean DEFAULT true,
  "created_at" datetime
);

CREATE TABLE "modules" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" int,
  "title" varchar,
  "description" varchar,
  "order" int,
  "required_xp" int DEFAULT 0,
  "xp_reward" int DEFAULT 10,
  "estimated_time" int,
  "is_locked" boolean DEFAULT false,
  "created_at" datetime
);

CREATE TABLE "module_prerequisites" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "module_id" int,
  "prerequisite_id" int
);

CREATE TABLE "lessons" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "module_id" int,
  "title" varchar,
  "description" varchar,
  "order" int,
  "xp_reward" int DEFAULT 5,
  "estimated_time" int,
  "created_at" datetime
);

CREATE TABLE "exercises" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lesson_id" int,
  "type" ExerciseType,
  "question" varchar,
  "instruction" varchar,
  "order" int,
  "xp_reward" int DEFAULT 1,
  "time_limit" int,
  "created_at" datetime
);

CREATE TABLE "exercise_options" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "exercise_id" int,
  "text" varchar,
  "is_correct" boolean,
  "image_src" varchar,
  "audio_src" varchar,
  "order" int
);

CREATE TABLE "exercise_progresses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "exercise_id" int,
  "completed" boolean DEFAULT false,
  "completed_at" datetime
);

CREATE TABLE "german_sounds" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "symbol" varchar,
  "exampleWord" varchar,
  "audio_src" varchar,
  "type" SoundType,
  "created_at" datetime
);

CREATE TABLE "sound_groups" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "order" int,
  "created_at" datetime
);

CREATE TABLE "sound_group_sounds" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sound_id" int,
  "group_id" int
);

CREATE UNIQUE INDEX ON "module_prerequisites" ("module_id", "prerequisite_id");

CREATE UNIQUE INDEX ON "sound_group_sounds" ("sound_id", "group_id");

ALTER TABLE "modules" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "module_prerequisites" ADD FOREIGN KEY ("module_id") REFERENCES "modules" ("id");

ALTER TABLE "module_prerequisites" ADD FOREIGN KEY ("prerequisite_id") REFERENCES "modules" ("id");

ALTER TABLE "lessons" ADD FOREIGN KEY ("module_id") REFERENCES "modules" ("id");

ALTER TABLE "exercises" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id");

ALTER TABLE "exercise_options" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "exercise_progresses" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "sound_group_sounds" ADD FOREIGN KEY ("sound_id") REFERENCES "german_sounds" ("id");

ALTER TABLE "sound_group_sounds" ADD FOREIGN KEY ("group_id") REFERENCES "sound_groups" ("id");
